version: "3.7"

services:
  etcd:
    image: "bitnami/etcd:3.5"
    container_name: "etcd"
    # 总是重启
    restart: "always"
    ports:
      - 2379:2379
    environment:
      # 时区设置
      - TZ=Asia/Shanghai
      # 允许无认证访问
      - ALLOW_NONE_AUTHENTICATION=yes
      # etcd 客户端访问URL
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    volumes:
      # 将数据映射到宿主机
      - etcd_data:/bitnami/etcd

volumes:
  etcd_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/docker/etcd/data"
